"""Package the demo data for Snowflake: one CSV per table plus ready-to-run SQL.

Reads the synthetic inputs (data/) and the model outputs (outputs/), checks every
table against schema.sql, and writes:

* ``snowflake_setup/data/<TABLE>.csv``: upper-case headers in schema column order,
  ISO dates, TRUE/FALSE booleans, empty = NULL. Load them with Snowsight's
  "Load Data" dialog or with ``load_from_stage.sql``.
* ``snowflake_setup/lumenvale_mmm_setup.sql``: schema.sql followed by INSERTs for
  every table. Paste into a Snowsight worksheet and "Run All": no tools needed.
* ``snowflake_setup/load_from_stage.sql``: PUT + COPY INTO for Snowflake CLI users.

Re-run after regenerating the data or refitting the model:

    uv run python snowflake_setup/build_bundle.py

DISCLAIMER: This project contains synthetic data and analysis created for
demonstration purposes only.
"""

from __future__ import annotations

import math
import re
import sys
from datetime import date, datetime
from pathlib import Path

import pandas as pd

SETUP_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SETUP_DIR.parent
sys.path.insert(0, str(PROJECT_DIR))

from mmm_data import (  # noqa: E402
    ALL_TABLES, DATABASE, SCENARIO_TABLE, SCHEMA, SNOWFLAKE_DATES, SNOWFLAKE_TIMESTAMPS,
    ensure_input_data, local_path, read_local,
)

SCHEMA_SQL = SETUP_DIR / "schema.sql"
DATA_OUT = SETUP_DIR / "data"
# Saved scenarios start empty: they are created live in the app.
BUNDLED_TABLES = tuple(t for t in ALL_TABLES if t != SCENARIO_TABLE)
INSERT_BATCH = 500


def schema_columns() -> dict[str, list[str]]:
    """Column names of every CREATE TABLE in schema.sql, in order."""
    sql = re.sub(r"--[^\n]*", "", SCHEMA_SQL.read_text())
    tables = {}
    for name, body in re.findall(r"CREATE (?:OR REPLACE )?TABLE (?:IF NOT EXISTS )?(\w+)\s*\((.*?)\);",
                                 sql, flags=re.S):
        body = re.sub(r"\([^)]*\)", "", body)  # drop NUMBER(14, 2) precision
        tables[name] = [col.split()[0] for col in body.split(",") if col.strip()]
    return tables


def table_frames(tables=BUNDLED_TABLES) -> dict[str, pd.DataFrame]:
    """Snowflake-ready frames: upper-case columns in schema order, typed values."""
    ensure_input_data()
    columns = schema_columns()
    frames = {}
    for table in tables:
        path = local_path(table)
        if not path.exists():
            raise FileNotFoundError(f"{path} not found. Run `uv run python ml/train_model.py` "
                                    "(and r/model_crosscheck.qmd for MMM_R_CROSSCHECK).")
        df = read_local(table)
        df.columns = [c.upper() for c in df.columns]
        expected = columns[table]
        if set(df.columns) != set(expected):
            raise ValueError(f"{table}: columns {sorted(df.columns)} do not match schema.sql "
                             f"{sorted(expected)}")
        df = df[expected].copy()
        for col in df.columns:
            if col.lower() in SNOWFLAKE_DATES:
                df[col] = pd.to_datetime(df[col]).dt.date
            elif col.lower() in SNOWFLAKE_TIMESTAMPS:
                df[col] = pd.to_datetime(df[col], utc=True).dt.tz_localize(None)
        frames[table] = df
    return frames


def sql_literal(v) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)) or v is pd.NaT:
        return "NULL"
    if isinstance(v, (bool,)) or type(v).__name__ == "bool_":
        return "TRUE" if v else "FALSE"
    if isinstance(v, (pd.Timestamp, datetime)):
        return f"'{v:%Y-%m-%d %H:%M:%S}'"
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    return repr(v.item() if hasattr(v, "item") else v)


def write_csvs(frames: dict[str, pd.DataFrame]) -> None:
    DATA_OUT.mkdir(exist_ok=True)
    for table, df in frames.items():
        out = df.copy()
        for col in out.columns:
            if out[col].dtype == bool:
                out[col] = out[col].map({True: "TRUE", False: "FALSE"})
        out.to_csv(DATA_OUT / f"{table}.csv", index=False, date_format="%Y-%m-%d %H:%M:%S")


def write_all_in_one_sql(frames: dict[str, pd.DataFrame]) -> Path:
    lines = [
        "-- Lumenvale Jewelers (FICTIONAL) - Marketing Mix demo: schema AND data, one file.",
        "-- Generated by snowflake_setup/build_bundle.py. Do not edit by hand.",
        "-- Snowsight: open a worksheet, paste this file, choose a warehouse, Run All.",
        "--",
        "-- DISCLAIMER: This project contains synthetic data and analysis created for",
        "-- demonstration purposes only.",
        "",
        SCHEMA_SQL.read_text().strip(),
        "",
        "-- ===========================================================================",
        "-- Data",
        "-- ===========================================================================",
    ]
    for table, df in frames.items():
        cols = ", ".join(df.columns)
        lines.append(f"\n-- {table}: {len(df):,} rows")
        records = df.astype(object).itertuples(index=False)
        values = [f"({', '.join(sql_literal(v) for v in r)})" for r in records]
        for i in range(0, len(values), INSERT_BATCH):
            lines.append(f"INSERT INTO {table} ({cols}) VALUES\n" + ",\n".join(values[i:i + INSERT_BATCH]) + ";")
    lines.append("\n-- Check: row counts per table")
    lines.append("\nUNION ALL\n".join(
        f"SELECT '{t}' AS TABLE_NAME, COUNT(*) AS N_ROWS FROM {t}" for t in frames) + ";")
    out = SETUP_DIR / "lumenvale_mmm_setup.sql"
    out.write_text("\n".join(lines) + "\n")
    return out


def write_stage_sql(frames: dict[str, pd.DataFrame]) -> Path:
    lines = [
        "-- Load snowflake_setup/data/*.csv with PUT + COPY INTO (Snowflake CLI or SnowSQL).",
        "-- Generated by snowflake_setup/build_bundle.py. Run from the project folder, after schema.sql:",
        "--   snow sql -f snowflake_setup/schema.sql",
        "--   snow sql -f snowflake_setup/load_from_stage.sql",
        "--",
        "-- DISCLAIMER: This project contains synthetic data and analysis created for",
        "-- demonstration purposes only.",
        "",
        f"USE SCHEMA {DATABASE}.{SCHEMA};",
        "",
        "CREATE OR REPLACE FILE FORMAT LUMENVALE_CSV TYPE = CSV SKIP_HEADER = 1",
        "    FIELD_OPTIONALLY_ENCLOSED_BY = '\"' EMPTY_FIELD_AS_NULL = TRUE;",
        "CREATE OR REPLACE TEMPORARY STAGE LUMENVALE_LOAD FILE_FORMAT = LUMENVALE_CSV;",
        "PUT file://snowflake_setup/data/*.csv @LUMENVALE_LOAD AUTO_COMPRESS = TRUE OVERWRITE = TRUE;",
        "",
    ]
    for table in frames:
        lines.append(f"COPY INTO {table} FROM @LUMENVALE_LOAD/{table}.csv.gz ON_ERROR = ABORT_STATEMENT;")
    out = SETUP_DIR / "load_from_stage.sql"
    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> None:
    frames = table_frames()
    write_csvs(frames)
    for table, df in frames.items():
        print(f"  {table:<28} {len(df):>6,} rows -> snowflake_setup/data/{table}.csv")
    print(f"  wrote {write_all_in_one_sql(frames).relative_to(PROJECT_DIR)}")
    print(f"  wrote {write_stage_sql(frames).relative_to(PROJECT_DIR)}")


if __name__ == "__main__":
    main()
